# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo-dev
    restart: 'no'
    ports:
      - 27017:27017

#   mongo-express:
#     image: mongo-express
#     restart: 'no'
#     depends_on:
#       mongo:
#         condition: service_healthy
#     ports:
#       - 8081:8081
#     networks: 
#       - mongo-compose-network
#     environment:
#       - ME_CONFIG_MONGODB_SERVER=mongo
#       - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
#       - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo
#       - ME_CONFIG_BASICAUTH_USERNAME=mongo
#       - ME_CONFIG_BASICAUTH_PASSWORD=mongo

# networks:
#   mongo-compose-network:
#     driver: bridge